version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      PROJECT_ID:
      PRIVATE_KEY:
      CLIENT_EMAIL:

    depends_on:
      - db

  db:
    image: mysql:5.7.19
    container_name: nestAPI-mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
